apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: netflix-ui-monitor
  labels:
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      app: netflix-ui
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s

