apiVersion: v1
kind: Service
metadata:
  name: netflix-ui
  labels:
    app: netflix-ui
    release: kube-prometheus
spec:
  type: LoadBalancer
  selector:
    app: netflix-ui
  ports:
    - name: http
      port: 80
      targetPort: 80
